pipeline {

    agent any

    environment {

        REGISTRY = "host.minikube.internal:5000"

        IMAGE = "flask-app"

    }

    stages {

        stage('Checkout') {

            steps {

                checkout scm

            }

        }

        stage('Build Docker') {

            steps {

                sh '''

                 docker build \
                 -t flask-app:${BUILD_NUMBER} \
                 app/

                 '''

             } 

        }

    }

}
